name: Deploy

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'PyPI username'
        required: true
      password:
        description: 'PyPI password'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.7'
      - run: make install-dev
      - run: make build
      - env:
          TWINE_USERNAME: ${{ github.events.inputs.username }}
          TWINE_PASSWORD: ${{ github.events.inputs.password }}
        run: make deploy
