name: Pull request checks

on:
  pull_request:
    branches:
      - 'staging'

jobs:
  title-check:
    runs-on: ubuntu-latest
    steps:
    - uses: thehanimo/pr-title-checker@v1.4.0
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  checks:
    uses: ./.github/workflows/callable-common-checks.yml
